# Usa la imagen oficial de MailHog
FROM mailhog/mailhog:latest

# Aquí puedes agregar configuraciones personalizadas si es necesario.
# Por ejemplo, si deseas usar un archivo de configuración de MailHog.
# COPY custom_config.json /etc/mailhog/config.json

# Exponer puertos
EXPOSE 1025 8025